#Write a Python program that uses a for loop to print the numbers from 1 to 10

# Use a for loop to print numbers from 1 to 10
# the for loop iterates over the numbers generated by the range(1, 11) function, which produces numbers from 1 to 10
for number in range(1, 11):
    print(number)

# Print a message after the loop
print("End of program")
## the for loop iterates over the numbers generated by the range(1, 11) 
